<?php

namespace App\Core;

class Respond {
	public const HTTP_CONTINUE                             = 100;
	public const HTTP_SWITCHING_PROTOCOLS                  = 101;
	public const HTTP_PROCESSING                           = 102;                                    // RFC2518
	public const HTTP_EARLY_HINTS                          = 103;                                    // RFC8297
	public const HTTP_OK                                   = 200;
	public const HTTP_CREATED                              = 201;
	public const HTTP_ACCEPTED                             = 202;
	public const HTTP_NON_AUTHORITATIVE_INFORMATION        = 203;
	public const HTTP_NO_CONTENT                           = 204;
	public const HTTP_RESET_CONTENT                        = 205;
	public const HTTP_PARTIAL_CONTENT                      = 206;
	public const HTTP_MULTI_STATUS                         = 207;                                    // RFC4918
	public const HTTP_ALREADY_REPORTED                     = 208;                                    // RFC5842
	public const HTTP_IM_USED                              = 226;                                    // RFC3229
	public const HTTP_MULTIPLE_CHOICES                     = 300;
	public const HTTP_MOVED_PERMANENTLY                    = 301;
	public const HTTP_FOUND                                = 302;
	public const HTTP_SEE_OTHER                            = 303;
	public const HTTP_NOT_MODIFIED                         = 304;
	public const HTTP_USE_PROXY                            = 305;
	public const HTTP_TEMPORARY_REDIRECT                   = 307;
	public const HTTP_PERMANENTLY_REDIRECT                 = 308;                                    // RFC7238
	public const HTTP_BAD_REQUEST                          = 400;
	public const HTTP_UNAUTHORIZED                         = 401;
	public const HTTP_PAYMENT_REQUIRED                     = 402;
	public const HTTP_FORBIDDEN                            = 403;
	public const HTTP_NOT_FOUND                            = 404;
	public const HTTP_METHOD_NOT_ALLOWED                   = 405;
	public const HTTP_NOT_ACCEPTABLE                       = 406;
	public const HTTP_PROXY_AUTHENTICATION_REQUIRED        = 407;
	public const HTTP_REQUEST_TIMEOUT                      = 408;
	public const HTTP_CONFLICT                             = 409;
	public const HTTP_GONE                                 = 410;
	public const HTTP_LENGTH_REQUIRED                      = 411;
	public const HTTP_PRECONDITION_FAILED                  = 412;
	public const HTTP_REQUEST_ENTITY_TOO_LARGE             = 413;
	public const HTTP_REQUEST_URI_TOO_LONG                 = 414;
	public const HTTP_UNSUPPORTED_MEDIA_TYPE               = 415;
	public const HTTP_REQUESTED_RANGE_NOT_SATISFIABLE      = 416;
	public const HTTP_EXPECTATION_FAILED                   = 417;
	public const HTTP_I_AM_A_TEAPOT                        = 418;                                    // RFC2324
	public const HTTP_MISDIRECTED_REQUEST                  = 421;                                    // RFC7540
	public const HTTP_UNPROCESSABLE_ENTITY                 = 422;                                    // RFC4918
	public const HTTP_LOCKED                               = 423;                                    // RFC4918
	public const HTTP_FAILED_DEPENDENCY                    = 424;                                    // RFC4918
	public const HTTP_TOO_EARLY                            = 425;                                    // RFC-ietf-httpbis-replay-04
	public const HTTP_UPGRADE_REQUIRED                     = 426;                                    // RFC2817
	public const HTTP_PRECONDITION_REQUIRED                = 428;                                    // RFC6585
	public const HTTP_TOO_MANY_REQUESTS                    = 429;                                    // RFC6585
	public const HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE      = 431;                                    // RFC6585
	public const HTTP_UNAVAILABLE_FOR_LEGAL_REASONS        = 451;                                    // RFC7725
	public const HTTP_INTERNAL_SERVER_ERROR                = 500;
	public const HTTP_NOT_IMPLEMENTED                      = 501;
	public const HTTP_BAD_GATEWAY                          = 502;
	public const HTTP_SERVICE_UNAVAILABLE                  = 503;
	public const HTTP_GATEWAY_TIMEOUT                      = 504;
	public const HTTP_VERSION_NOT_SUPPORTED                = 505;
	public const HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL = 506;                                    // RFC2295
	public const HTTP_INSUFFICIENT_STORAGE                 = 507;                                    // RFC4918
	public const HTTP_LOOP_DETECTED                        = 508;                                    // RFC5842
	public const HTTP_NOT_EXTENDED                         = 510;                                    // RFC2774
	public const HTTP_NETWORK_AUTHENTICATION_REQUIRED      = 511;                                    // RFC6585
	
	public const STATUS_TEXTS = [
		self::HTTP_CONTINUE => 'Continue',
		self::HTTP_SWITCHING_PROTOCOLS => 'Switching Protocols',
		self::HTTP_PROCESSING => 'Processing',                        // RFC2518
		self::HTTP_EARLY_HINTS => 'Early Hints',
		self::HTTP_OK => 'OK',
		self::HTTP_CREATED => 'Created',
		self::HTTP_ACCEPTED => 'Accepted',
		self::HTTP_NON_AUTHORITATIVE_INFORMATION => 'Non-Authoritative Information',
		self::HTTP_NO_CONTENT => 'No Content',
		self::HTTP_RESET_CONTENT => 'Reset Content',
		self::HTTP_PARTIAL_CONTENT => 'Partial Content',
		self::HTTP_MULTI_STATUS => 'Multi-Status',                        // RFC4918
		self::HTTP_ALREADY_REPORTED => 'Already Reported',                    // RFC5842
		self::HTTP_IM_USED => 'IM Used',                            // RFC3229
		self::HTTP_MULTIPLE_CHOICES => 'Multiple Choices',
		self::HTTP_MOVED_PERMANENTLY => 'Moved Permanently',
		self::HTTP_FOUND => 'Found',
		self::HTTP_SEE_OTHER => 'See Other',
		self::HTTP_NOT_MODIFIED => 'Not Modified',
		self::HTTP_USE_PROXY => 'Use Proxy',
		self::HTTP_TEMPORARY_REDIRECT => 'Temporary Redirect',
		self::HTTP_PERMANENTLY_REDIRECT => 'Permanent Redirect',                // RFC7238
		self::HTTP_BAD_REQUEST => 'Bad Request',
		self::HTTP_UNAUTHORIZED => 'Unauthorized',
		self::HTTP_PAYMENT_REQUIRED => 'Payment Required',
		self::HTTP_FORBIDDEN => 'Forbidden',
		self::HTTP_NOT_FOUND => 'Not Found',
		self::HTTP_METHOD_NOT_ALLOWED => 'Method Not Allowed',
		self::HTTP_NOT_ACCEPTABLE => 'Not Acceptable',
		self::HTTP_PROXY_AUTHENTICATION_REQUIRED => 'Proxy Authentication Required',
		self::HTTP_REQUEST_TIMEOUT => 'Request Timeout',
		self::HTTP_CONFLICT => 'Conflict',
		self::HTTP_GONE => 'Gone',
		self::HTTP_LENGTH_REQUIRED => 'Length Required',
		self::HTTP_PRECONDITION_FAILED => 'Precondition Failed',
		self::HTTP_REQUEST_ENTITY_TOO_LARGE => 'Content Too Large',                    // RFC-ietf-httpbis-semantics
		self::HTTP_REQUEST_URI_TOO_LONG => 'URI Too Long',
		self::HTTP_UNSUPPORTED_MEDIA_TYPE => 'Unsupported Media Type',
		self::HTTP_REQUESTED_RANGE_NOT_SATISFIABLE => 'Range Not Satisfiable',
		self::HTTP_EXPECTATION_FAILED => 'Expectation Failed',
		self::HTTP_I_AM_A_TEAPOT => 'I\'m a teapot',                        // RFC2324
		self::HTTP_MISDIRECTED_REQUEST => 'Misdirected Request',                // RFC7540
		self::HTTP_UNPROCESSABLE_ENTITY => 'Unprocessable Content',                // RFC-ietf-httpbis-semantics
		self::HTTP_LOCKED => 'Locked',                            // RFC4918
		self::HTTP_FAILED_DEPENDENCY => 'Failed Dependency',                    // RFC4918
		self::HTTP_TOO_EARLY => 'Too Early',                            // RFC-ietf-httpbis-replay-04
		self::HTTP_UPGRADE_REQUIRED => 'Upgrade Required',                    // RFC2817
		self::HTTP_PRECONDITION_REQUIRED => 'Precondition Required',                // RFC6585
		self::HTTP_TOO_MANY_REQUESTS => 'Too Many Requests',                    // RFC6585
		self::HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE => 'Request Header Fields Too Large',    // RFC6585
		self::HTTP_UNAVAILABLE_FOR_LEGAL_REASONS => 'Unavailable For Legal Reasons',        // RFC7725
		self::HTTP_INTERNAL_SERVER_ERROR => 'Internal Server Error',
		self::HTTP_NOT_IMPLEMENTED => 'Not Implemented',
		self::HTTP_BAD_GATEWAY => 'Bad Gateway',
		self::HTTP_SERVICE_UNAVAILABLE => 'Service Unavailable',
		self::HTTP_GATEWAY_TIMEOUT => 'Gateway Timeout',
		self::HTTP_VERSION_NOT_SUPPORTED => 'HTTP Version Not Supported',
		self::HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL => 'Variant Also Negotiates',            // RFC2295
		self::HTTP_INSUFFICIENT_STORAGE => 'Insufficient Storage',                // RFC4918
		self::HTTP_LOOP_DETECTED => 'Loop Detected',                        // RFC5842
		self::HTTP_NOT_EXTENDED => 'Not Extended',                        // RFC2774
		self::HTTP_NETWORK_AUTHENTICATION_REQUIRED => 'Network Authentication Required'   // RFC6585
	];
}